# Generated by Django 4.2.1 on 2023-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
