# Generated by Django 4.2.2 on 2023-06-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_event_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
    ]
